export const DISPLAY_EMPLOYEE = 'DISPLAY_EMPLOYEE'
export const CHOOSE_COUNTRY = 'CHOOSE_COUNTRY'

export const FETCH_EMPLOYEES = 'FETCH_EMPLOYEES'
export const FETCH_EMPLOYEES_SUCCESS = 'FETCH_EMPLOYEES_SUCCESS'
export const FETCH_EMPLOYEES_FAILURE = 'FETCH_EMPLOYEES_FAILURE'
